os: linux
dist: xenial

language: c++

before_install:
  - pip install --user cpp-coveralls

addons:
  sonarcloud:
    organization: "seekerk-github"

script:
  - cmake .
  - make
  - make test

after_success:
  - coveralls --root . -E ".*external.*" -E ".*tests.*" -E ".*CMakeFiles.*"
  - build-wrapper-linux-x86-64 --out-dir bw-output make clean all
  - sonar-scanner

cache:
  directories:
  - '$HOME/.m2/repository'
  - '$HOME/.sonar/cache'

notifications:
  email: false
